#!/bin/bash
echo  "================== post-checkout ====================="
echo $@

prevHEAD=$1                                                                      
newHEAD=$2                                                                       
checkoutType=$3                                                                  

[[ $checkoutType == 1 ]] && checkoutType='branch' ||                             
                            checkoutType='file' ;                                

echo 'Checkout type: '$checkoutType                                              
echo '    prev HEAD: '`git name-rev --name-only $prevHEAD`
echo '     new HEAD: '`git name-rev --name-only $newHEAD`

echo 'new Branch Name: '`git rev-parse --abbrev-ref HEAD`
